############## NFL Big Data Bowl Kaggle Competition ######################

# Data loading
loading:
  # Specify which database and table the data is contained in
  database: 'nfl_data_bowl'
  user: 'postgres'
  drv: 'PostgreSQL'
  host: 'localhost'
  # Set how many rows are required (int or 'all')
  rows: 100
